# Generated by Django 4.2.1 on 2023-05-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genre',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Film',
            new_name='ProductDescription',
        ),
    ]
