# Generated by Django 4.2.1 on 2023-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0002_rename_genre_product_rename_film_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=750),
        ),
    ]
