# Generated by Django 4.2.1 on 2023-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0004_product_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='', max_length=700),
        ),
    ]
