# Generated by Django 4.2.1 on 2023-05-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0008_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=750),
        ),
    ]
