# Generated by Django 4.2.1 on 2023-05-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0009_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDescription',
        ),
    ]
