# Generated by Django 4.2.1 on 2023-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0015_alter_productdescription_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='price',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
