# Generated by Django 4.2.1 on 2023-05-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0016_alter_productdescription_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='about_this_item',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='compatible_device',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='compatible_models',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='connectivity_technology',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='connector_type',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='input_voltage',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='mounting_type',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='special_features',
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='availability',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='delivery',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='name',
            field=models.CharField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='rating',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='shipping_import_details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='total_rating',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
