# Generated by Django 4.2.1 on 2023-05-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0017_remove_productdescription_about_this_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='about_this_item',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='compatible_device',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='compatible_models',
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='connectivity_technology',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='connector_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='mounting_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productdescription',
            name='special_features',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
