# Generated by Django 4.2.1 on 2023-05-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0019_remove_productdescription_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='price',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='rating',
            field=models.FloatField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
