# Generated by Django 4.2.1 on 2023-05-08 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0021_alter_productdescription_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='compatible_device',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='compatible_models',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='connectivity_technology',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='connector_type',
        ),
    ]
