# Generated by Django 4.2.1 on 2023-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0023_alter_productdescription_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdescription',
            name='img',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
