# Generated by Django 4.2.1 on 2023-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0025_productdescription_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='connectivity_technology',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
