# Generated by Django 4.2.1 on 2023-05-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0026_alter_productdescription_connectivity_technology_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
