# Generated by Django 4.2.1 on 2023-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0027_alter_productdescription_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='connectivity_technology',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='connector_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='delivery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='input_voltage',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='productdescription',
            name='total_rating',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
