# Generated by Django 4.2.1 on 2023-05-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_bot', '0028_alter_productdescription_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdescription',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='input_voltage',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='mounting_type',
        ),
        migrations.RemoveField(
            model_name='productdescription',
            name='special_features',
        ),
    ]
